Traceback (most recent call last):
  File "/Users/alissahuskey/Library/Caches/pypoetry/virtualenvs/python-class-Xq3GLStO-py3.8/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/alissahuskey/Library/Caches/pypoetry/virtualenvs/python-class-Xq3GLStO-py3.8/lib/python3.8/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/alissahuskey/Library/Caches/pypoetry/virtualenvs/python-class-Xq3GLStO-py3.8/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/alissahuskey/Library/Caches/pypoetry/virtualenvs/python-class-Xq3GLStO-py3.8/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/alissahuskey/.pyenv/versions/3.8.1/lib/python3.8/asyncio/base_events.py", line 612, in run_until_complete
    return future.result()
  File "/Users/alissahuskey/Library/Caches/pypoetry/virtualenvs/python-class-Xq3GLStO-py3.8/lib/python3.8/site-packages/nbclient/client.py", line 540, in async_execute
    await self.async_execute_cell(
  File "/Users/alissahuskey/Library/Caches/pypoetry/virtualenvs/python-class-Xq3GLStO-py3.8/lib/python3.8/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/alissahuskey/Library/Caches/pypoetry/virtualenvs/python-class-Xq3GLStO-py3.8/lib/python3.8/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------

if answer < 0:
    print("Answer must be a positive number")
elif answer > 5:
    print("Answer must be less than five.")
else:
    print("Your answer was:", answer)


------------------

[38;2;231;233;219;01m---------------------------------------------------------------------------[38;2;231;233;219m
[38;2;239;97;85mNameError[38;2;231;233;219m                                 Traceback (most recent call last)
[38;2;254;196;24m<ipython-input-5-5bcdd25294a6>[38;2;231;233;219m in [38;2;239;97;85m<module>[38;2;249;155;21m[38;2;231;233;219m
[38;2;249;155;21m----> 1[38;2;249;155;21m [38;2;129;91;164mif[0m [38;2;231;233;219manswer[0m [38;2;91;196;191m<[0m [38;2;249;155;21m0[0m[38;2;91;196;191m:[0m[38;2;231;233;219m[0m[38;2;231;233;219m[0m[0m
[38;2;231;233;219m[38;2;249;155;21m      2[38;2;231;233;219m     [38;2;231;233;219mprint[0m[38;2;91;196;191m([0m[38;2;72;182;133m"Answer must be a positive number"[0m[38;2;91;196;191m)[0m[38;2;231;233;219m[0m[38;2;231;233;219m[0m[0m
[38;2;249;155;21m      3[38;2;231;233;219m [38;2;129;91;164melif[0m [38;2;231;233;219manswer[0m [38;2;91;196;191m>[0m [38;2;249;155;21m5[0m[38;2;91;196;191m:[0m[38;2;231;233;219m[0m[38;2;231;233;219m[0m[0m
[38;2;249;155;21m      4[38;2;231;233;219m     [38;2;231;233;219mprint[0m[38;2;91;196;191m([0m[38;2;72;182;133m"Answer must be less than five."[0m[38;2;91;196;191m)[0m[38;2;231;233;219m[0m[38;2;231;233;219m[0m[0m
[38;2;249;155;21m      5[38;2;231;233;219m [38;2;129;91;164melse[0m[38;2;91;196;191m:[0m[38;2;231;233;219m[0m[38;2;231;233;219m[0m[0m

[38;2;239;97;85mNameError[38;2;231;233;219m: name 'answer' is not defined
NameError: name 'answer' is not defined

